### ISSUE TITLE
Use an external Zookeeper and optional graphite and tabix

### ISSUE THREAD

**Issue by Gillani0** [plutov/clickhouse-helm#2]
Hi,

The helm chart should be able to use the external zookeeper by given the link (so enable true or false). Furthermore, the graphite and tabix should be optional, hence one should be able to enable and disable them. Otherwise, good work :)

Syd

**Comment by plutov** [comment]
Actually tabix and graphite are already optional:
```# tabix.io web UI
tabix:
  enabled: false
  lbEnabled: false

# Add monitoring with graphite
graphite:
  enabled: false
  lbEnabled: false```

**Comment by Gillani0** [comment]
Perfect!!
Yeah sorry just realised it. Cheers
