### ISSUE TITLE
 couldn't parse image reference "gcr.io/google_samples/k8szk:v1:v1": invalid reference format

### ISSUE THREAD

**Issue by andrii29** [plutov/clickhouse-helm#6]
please remove tag from **repository** variable
https://github.com/plutov/clickhouse-helm/blob/master/clickhouse/templates/zookeeper.yaml#L33
https://github.com/plutov/clickhouse-helm/blob/master/clickhouse/values.yaml#L27-L28

**Comment by plutov** [comment]
Good catch!

**Comment by plutov** [comment]
Done
