### ISSUE TITLE
Tempalte namespace hardcode

### ISSUE THREAD

**Issue by raider444** [plutov/clickhouse-helm#7]
Hi, there is default namespace in template configd.yaml for all services (zk, ClickHouse, graphite) in host definition. Please change `default` to `{{.Release.Namespace}}`.

**Comment by plutov** [comment]
I added `clusterDNS` value to values.yaml

**Comment by raider444** [comment]
Now I get error
`Wait helm template failed. Error: render error in "clickhouse/templates/configd.yaml": template: clickhouse/templates/configd.yaml:17:61: executing "clickhouse/templates/configd.yaml" at <.Values.clusterDNS>: can't evaluate field Values in type int : exit status 1`

clusterDNS is defined as clickhouse.svc.cluster.local

**Comment by plutov** [comment]
Oh, thanks for spotting it. My fault, just pushed a fix
